### ISSUE TITLE
TreuLove looks worse on R4 than on R3/R3A

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#112]
@paich64 In the Skype R5 channel we talked about TreuLove on Deft's R4 and you confirmed that it looked worse than TreuLove on V5 on your R3A machine. Can you elaborate what "looks worse" means? Here is a screenshot of the relevant part of our Skype conversation:

<img width="1075" alt="grafik" src="https://github.com/MJoergen/C64MEGA65/assets/6825267/28404d01-e0dc-407a-8c0b-1878287c7432">

**Comment by paich64** [comment]
@MJoergen @sy2002 before i provide the relevant information, could you please confirm if the "post batch2" REU fix only occured in V5A9 or did you also make other improvement after v5A9 ? I know that V5A11 was a core which provided REU debug information but i don't remember if after V5A11 you made other improvements ? I can't find anything in the readme file related to REU improvement after V5A9.

**Comment by paich64** [comment]
Thisis basically all i have : [inofficial.md](https://github.com/MJoergen/C64MEGA65/files/13369977/inofficial.md)

**Comment by sy2002** [comment]
@paich64 Yes, you are right: The HyperRAM errata was done in Alpha 9 for V5 as described in inofficial.md . Afterwards, no other relevant HyperRAM fixes were done or HyperRAM work was done. So we can compare: Release Version of V5 with the version that run on Deft's R4 board.

**Comment by paich64** [comment]
@sy2002 thanks a lot for clarifying as i have to browse through my conversations history with @muse and @mpryon in order to provide the best possible picture of the current situation as well as linking the relevant videos. I will update here as soon as i have retrieved a clear picture of the current situation.

**Comment by sy2002** [comment]
@paich64 Hey can you please test if this core here [c64m65v51-d4d294b.zip](https://github.com/MJoergen/C64MEGA65/files/13404567/c64m65v51-d4d294b.zip) still runs TreuLove flawlessly on YOUR R3A machine?

**Comment by paich64** [comment]
@sy2002 @MJoergen I confirm The demo keeps running the exact same way with no additional glitches using this specific core on my R3A board.
full video : https://www.youtube.com/watch?v=wffczD32b2U
the demo starts here : https://www.youtube.com/watch?v=wffczD32b2U&t=250s
note : my video capture device captured at 30FPS... :)

**Comment by sy2002** [comment]
So @MJoergen I guess this is the feedback you wanted: The current develop branch still works like a charme on an R3A board but it does not on an (or specifically Deft's) R4 board. What are sensible next steps.  (P.S. Thank you @paich64 for your support.)

**Comment by MJoergen** [comment]
Deft reported on December 9 2023 (7:21 PM)

"Michael the problems I encountered in TREU LOVE seem to be gone now .. good job!!"
