### ISSUE TITLE
Confirm that flashing an EF1CR works on R4

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#113]
Since this uses different mechanisms, you should test to flash a small game (like 16KB) and a large game (like multiple hundreds of kB).

Here is a copy/paste of info that I shared with you on Skype - but the good news is that you already have several disk images from deft:

1) First of all, you should drill a hole in the cartridge and read everything that I have written here:
https://github.com/MJoergen/C64MEGA65/blob/master/doc/cartridges.md#easyflash-1-and-easyflash-1cr

2) To get started, here is an easy first test: Flash a small game that does not need to be split into multiple D64 disk images
2a) Nice specimen for this kind of test are the participants of the 16 KiloByte Game competition from RGCD:
https://csdb.dk/search/?seinsel=events&search=rgcd&Go.x=0&Go.y=0

For example take this here (Alienator):
https://csdb.dk/release/?id=146978

2b) You need to create a D64 disk image and put the *.crt file on the D64 image:
https://codebase64.org/doku.php?id=base:tools_for_putting_files_into_a_.d64_image
or
https://style64.org/dirmaster  (Windows only)
or
https://droid64.sourceforge.net/ (Java, runs on Linux=

2c) When you first insert a brand new EF 1CR from Daniel, it autostarts the flasher tool and then asks you for a disk drive, mount the D64 file with the game and then use the flasher tool.

2d) After that, reboot the C64 core and the game should start (make sure that your core is in the "Hardware" mode for Cartridges and not in the Emulation mode before restarting/resetting)

3) The test in (2) only tests trivial stuff, i.e. no bank switching and no complicated signals. Therefore the next test needs to be: Use a big game, such as A Pig Quest or Eye of the Beholder. Caveat: You need to split this game into multiple files and but these files onto multiple D64 disk images. This is the main reason, why I bought an SD2IEC:
https://nc92.eu/products/sd2iec-lcd-sd-card-reader-for-commodore-64-c128-vic-20-c16-plus4
Kills two birds with one stone: With this device you will be able to test the IEC port of the MEGA65 - AND - you will never need to wrap a CRT file into a D64 disk image or even split a CRT file into multiple CRT files and then put them into D64 disk images ...   Because Daniel's firmware can cope with the SD2IEC and directly read CRT files from it - also large ones such as A Pig Quest or EOB.

3a) Since you don't have an SD2IEC, yet (I assume?) you will  need the EasySplit tool. Might be that it just runs under windows. Please right the section in the documentation that I posted above in (1) - it contains the link to EasySplit: You need to take the EasyFlash version of a large CRT file (they come in mutiple versions, one of them is EasyFlash) and then you need to create a bunch of empty D64 images and then put the split files (made by easyflash) into all these images and then use Daniel's tool to flash. I made a YouTube HowTo video - the link is in the documentation above in (1).

3b) You will need to work with the switch on the EF1CR to re-flash it, after you flashed the simple game in (2) and you will need to download Daniel's flashing tool, because it will be overwritten when you do (2). How to: See documentationin (1).

**Comment by MJoergen** [comment]
Verified on R5 with Eye of the Beholder.
