### ISSUE TITLE
Final Cart III behaviour

### ISSUE THREAD

**Issue by CINJ** [MJoergen/C64MEGA65#114]
I just tested out a Final Cart III on the v5 core in an R3 and it worked - but has some weird behaviours.
1. does not reset using FCIII reset button
2. freeze button on FCIII only works very intermittently on start, after that - no work at all
3. first boot and hardware (mega) reset button often shows blank light and dark blue screen (ie: CBM with missing text symptomatic of messed up ROM when repairing a C64)

note: this is not a new FCIII, its an original one that works on regular C64 and C64c

**Comment by sy2002** [comment]
Hi @CINJ , thank you for reporting your issues. I saw that you opened and then closed this issue. So you might have seen that we have some known issues with the FCIII in our cartridge documentation: https://github.com/MJoergen/C64MEGA65/blob/develop/doc/cartridges.md#final-cartridge-iii

And also an existing GitHub issue: https://github.com/MJoergen/C64MEGA65/issues/77

In general: One R3/R3A boards, we will never hit 100% with the FCIII - but the upcoming R5 board (2024 batches) will allow us to be even more compatible.
