### ISSUE TITLE
Color palette a bit pale

### ISSUE THREAD

**Issue by micv2** [MJoergen/C64MEGA65#154]
Hello, 

the color palette looks a bit pale on my VGA monitor. Is it possible to increase the intensity of the color palette?

Best regards,
MiC

**Comment by sy2002** [comment]
@micv2 Thank you for your feature request. The C64 core is outputting the closest possible approximation of the real C64's colors. We're in sync with MiSTer's latest color fixes:

https://github.com/MiSTer-devel/C64_MiSTer/issues/55
and
https://github.com/MiSTer-devel/C64_MiSTer/pull/56

See also: https://www.pepto.de/projects/colorvic/

I am closing this issue as WONTFIX
