### ISSUE TITLE
Feature request : Provide an option to flip the display for some games meant to be played the arcade way

### ISSUE THREAD

**Issue by paich64** [MJoergen/C64MEGA65#159]
There are a few games which are displayed the arcade way, like for example Phoenix : 

https://www.youtube.com/watch?v=cX_lGyQRTnI

https://csdb.dk/release/?id=205278

Unless one can physically rotate his monitor, it's not really possible to play them.

Now that we have the FPGA core technology, being able to rotate the display would make them playable at last.

Being able to flip by 90°/180°/270° would be perfect.

**Comment by sy2002** [comment]
For an analog output (using the VGA port), you cannot just flip the image, you would need to buffer it. This goes against our philosophy that the analog output is unprocessed and the pure image. For the digital output (HDMI) it is kind of "easily doable".
Bottom line: Doable, not trivial given the current M2M architecture and also given that we talk about 0.1% of the games and given that we have so many other feature requests, I am closing this one as NOT PLANNED.
