### ISSUE TITLE
Keep disk image mounted after reset

### ISSUE THREAD

**Issue by HovKlan-DH** [MJoergen/C64MEGA65#19]
Would it be possible to keep the disk image mounted after a soft and hard reset? E.g. if a demo fails, and we need to try a new setting (e.g. switching CIA 8521), then it would be faster, if the image already was mounted. You could even argue, this would be "real life behavior", as the disk would still be in the floppy drive, even after a power-off ;-)

Also if we are going through a lot of demos, and we need to (hard) reset in between, then we are as close as possible to the next item, not needing to go through a potential long directory structure.

That would of course only apply to disk images and not PRGs (future v5 stuff).

**Comment by sy2002** [comment]
While I understand the rationale behind this feature request from a usability perspective: The effort to implement this would need rather complicated and "dangerous" logic changes in the inner guts of the MiSTer core and make future updates from upstream rather complicated. So I am declining this one as "wontfix".
