### ISSUE TITLE
SIMCRT: Subsequent mounting sometimes needs additional reset

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#28]
The files that you need are in the 7z file "Commercial_Releases.7z" that I shared with you via Skype on 4/29/23:

* ZetaWing 1: `ZetaWing v1.2.1.crt`
* ZetaWing 2: `ZetaWing2 v1_01.crt`

### Reproduction:

1. Boot the core
2. Select "Simulate cartridge"
3. Do the following steps without leaving the On-Screen-Menu and do not wait long between the multiple boots: Switch to the next as soon as you see the title screen running:
3a) Boot ZetaWing 1
3b) Boot ZetaWing 2
3c) Boot ZetaWing 1
4. You will land on the Commodore start screen
5. But RESET starts the game without any problems

### Desired outcome:

Users can switch at will between cartridges: The core always starts the cartridge without an additional reset

**Comment by MJoergen** [comment]
Fixed in #8977c8b
