### ISSUE TITLE
Feature request: When in file browser, left/right arrows jump to top/bottom

### ISSUE THREAD

**Issue by MJoergen** [MJoergen/C64MEGA65#31]
### Current situation
When in the file browser, it's possible to use the left and right buttons to scroll a page up or down.

But if the cursor is in the middle of the first page, the left button does nothing. Similarly, when in the middle of the last page, the right button does nothing.

### Request
When the cursor is in the middle of the first page, the left button should jump to the top of the page. Similarly, when in the middle of the last page, the right button should jump to the bottom of the page.

**Comment by sy2002** [comment]
Done with commit 350397f
