### ISSUE TITLE
Bug in OSM: CRT file selector indication sometimes incorrect

### ISSUE THREAD

**Issue by MJoergen** [MJoergen/C64MEGA65#33]
### Observation
Sometimes I see in the OSM that a CRT file is chosen, but the menu item is not selected. I.e. I see the line
```
 CRT: C_2048.crt
```

### Expected behaviour
When a file is chosen, I expect the menu item to be selected, i.e.
```
=CRT: C_2048.crt
```

### Additional information
It seems like the menu selection is toggled, so every second time it is off, and every other time it is on.

**Comment by sy2002** [comment]
Thank you for reporting this. This is a bug.

**Comment by sy2002** [comment]
Fixed by commit https://github.com/MJoergen/C64MEGA65/commit/02840821999c2904c7050e2960fcd86065405f53
