### ISSUE TITLE
SIMCRT: Bruce Lee Duology: Crash after first menu, not loading

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#38]
Discord User SkulleateR#4575 reported (Quoting):

"Bruce Lee Duology: Crash after first menu, not loading"

I asked him to provide us with the `*.crt` file via Discord DM.

**Comment by paich64** [comment]
Not a bug, only the non official cracked releases do not work.
I just tested the official release (https://rebel-android.itch.io/bruce-lee-duology). It perfectly works on both Mister / Mega65 C64 core :)

**Comment by sy2002** [comment]
OK, thank you @paich64 . Since we want to support the community of makers around the C64, we want that the originals work, and don't care if the cracked versions work.
