### ISSUE TITLE
SIMCRT: Cartridge type 7 fails after initial screen

### ISSUE THREAD

**Issue by MJoergen** [MJoergen/C64MEGA65#39]
This is seen using this CRT file: Funplay_Codemasters_-_Fast_Food_Pro_Skateboard_Pro_Tennis.crt

The initial intro shows, but after selecting the first game, it crashes.

This is confirmed to work on MiSTer and also in VICE.

**Comment by MJoergen** [comment]
Fixed in commit 5fcfd60

**Comment by sy2002** [comment]
@paich64 can you please confirm that Beta 1 (WIP-V5-B1) fixes this issue?

**Comment by paich64** [comment]
I confirm Funplay_Codemasters_-_Fast_Food_Pro_Skateboard_Pro_Tennis.crt now plays as expected. The 3 games can be started and played :)
