### ISSUE TITLE
Finalize VERSIONS.md

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#49]
Finalize VERSIONS.md

**Comment by sy2002** [comment]
Done in current `develop` branch.

@MJoergen please proof-read https://github.com/MJoergen/C64MEGA65/blob/develop/VERSIONS.md
But ONLY Version 5 - we do not want to change "the past" :-)
Please close this issue as soon as you're done.

**Comment by MJoergen** [comment]
Done
