### ISSUE TITLE
Sprites not shown correctly

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#76]
User @Schwefelholz reported the following issue (https://github.com/sy2002/MiSTer2MEGA65/issues/17):

The game "Raid on Bungeling Bay" that shows a "ghost image" of the helicopter's rotor Blade here is how it looks:

![grafik](https://github.com/MJoergen/C64MEGA65/assets/6825267/2d3edc90-537e-46e1-aba7-b0f263ac2bdf)

And here is how it looks on a real C64 and/or on an Ultimate 64:

![grafik](https://github.com/MJoergen/C64MEGA65/assets/6825267/a7268a74-0553-4f26-af11-f54276dbdb0b)

@paich64 Can you please double-check / confirm if this also happens on the MiSTer?

**Comment by paich64** [comment]
Just tested the game on MEGA65 c64 core V5 beta3 : No such issue .....
![1686377503250](https://github.com/MJoergen/C64MEGA65/assets/6482872/c2c0cf69-6422-4454-a88b-a1388e7bacaa)

**Comment by Schwefelholz** [comment]
Hmm, that's strange. I had this issue on MEGA65 c64 core V5 beta3 as well.

Maybe just another copy of the game? I'll try once again and will report back.

Am 10. Juni 2023 08:12:13 MESZ schrieb paich64 ***@***.***>:

**Comment by sy2002** [comment]
@Schwefelholz This version is known to work without glitches:
[Raid_on_Bungeling_Bay.zip](https://github.com/MJoergen/C64MEGA65/files/11712031/Raid_on_Bungeling_Bay.zip)
I am closing this issue.
