### ISSUE TITLE
Long reset aka hard-reset does not reset "Eagle's Nest"

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#79]
This bug is a regression introduced in V5 as this worked in V4.

**Expected behavior (see also tests/README.md):**

* Short reset: Back to game's title screen
* Long reset: Reset C64, back to Basic

**What happens:**

A long reset does not return to Basic

**When was the regression introduced:**

* WIP-V5-A9, i.e. commit 65d8fc8 works
* Interestingly enough WIP-V5-A10, i.e. commit 9c336c2 also works, even though there,
  the new `handle_cold_start` mechanism was introduced
* WIP-V5-A23, i.e. commit e1c696d is the last version that works
* From WIP-V5-B1 on, i.e. commit 584972c it does not work any more

Here is a code comparison between these two commits:
https://github.com/MJoergen/C64MEGA65/compare/e1c696d..584972c

**Impact:**

It is very likely that this bug is not only affecting "Eagle's Nest" but also materializes itself in other situations where it will lead to either the reset itself not working or applications loaded after the reset not working properly.

**Comment by sy2002** [comment]
Confirmed by discord user mauricevg that Pac-Man is affected, too:
https://discord.com/channels/719326990221574164/794775503818588200/1121155136853639219

**Comment by sy2002** [comment]
Fixed.

**Comment by MauriceMEGA65** [comment]
I just discovered: Pac-man needed to have the hard reset to be fixed, which is done in one of the alpha versions.
However, I just encountered the following:

Hard-reset DOES properly reset the system, I'm back in the BASIC 2 or JiffyDOS screen
When I do a soft-reset AFTER the hard-reset, I'm back in the Pac-man welcome screen!?!?

**Comment by sy2002** [comment]
@MauriceMEGA65 I think this is "works as desgined". What happens on a real C64?

**Comment by MauriceMEGA65** [comment]
A real C64 does not have a reset button IIRC. It’s no dealbreaker of course, just I thought the hard-reset is like a power cycle on a real C64. But apparently the memory is not really reset as a soft-reset after the hard-reset seems to reinitialize what was in memory before the hard-reset.

**Comment by sy2002** [comment]
Yes, this is what I mean by "works as designed" :-) The hard reset does what a hard reset button (that was an extra gadget you could buy), did. We implemented this behavior: https://www.c64-wiki.com/wiki/Reset_Button

**Comment by MauriceMEGA65** [comment]
Ah! “_Previously used data in the [RAM](https://www.c64-wiki.com/wiki/RAM), especially [BASIC](https://www.c64-wiki.com/wiki/BASIC)-programs, survive this_”
Yes, all clear now! Thank you and sorry for the confusion!
