### ISSUE TITLE
Hang in All Hallows Eve by Atlantis (Compo winner at Zoo 2022)

### ISSUE THREAD

**Issue by mlund** [MJoergen/C64MEGA65#9]
The demo plays nicely until somewhere in disk 2 after the circular flame-sprites where it hangs. The demo can be found here:

https://demozoo.org/productions/314618/

Core: C64MEGA65-V4RC2.zip running on a PAL system.

**Comment by sy2002** [comment]
[C64MEGA65-dev-irqdisp.zip](https://github.com/MJoergen/C64MEGA65/files/10011912/C64MEGA65-dev-irqdisp.zip)

@mlund In the attached ZIP you will find an experimental version of the core that fixes the problem. Please test and confirm.

**Comment by mlund** [comment]
thanks for the swift fix - the demo now runs to the end!
