### ISSUE TITLE
5.1A2: OSM zoom is broken

### ISSUE THREAD

**Issue by sy2002** [MJoergen/C64MEGA65#99]
@paich64 (AmokPhaze) found this over the week-end testing 5.1A2: The OSM zoom is broken: Any setting other than 50% looks like this on HDMI and VGA:

![20231021_182728](https://github.com/MJoergen/C64MEGA65/assets/6825267/da266f26-23c7-4617-b681-6b977f12e580)

My gut feeling is that this has something to do with our refactored OSM component in M2M.

**Comment by MJoergen** [comment]
I just tried with V5.1A1, and there OSM Scaling works fine. So that supports your suspicion.

**Comment by MJoergen** [comment]
And indeed, trying with commit #d2e7616 reproduces the problem.

**Comment by MJoergen** [comment]
Fixed in commit bfedd13
